[project]
name = "training-gan-to-generate-clothes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.6.7",
    "torch>=2.4.1",
]
